PLAYER_START_BANK = 100 # dollars
BET_MULTIPLIERS = {"Win": 5, "Place": 3, "Show": 1}
DEFAULT_BET_SIZE = 10 # dollars
RACE_DISTANCE = 2000  # meters
SPEED_MIN = 200  # km/h
SPEED_MAX = 220  # km/h
AGILITY_MIN = 85
AGILITY_MAX = 100
CHARGING_MIN = 0.03
CHARGING_MAX = 0.15
TIME_COMPRESSION = 10  # Real-time compression factor
STRAIGHTAWAY_LENGTH = 750
TURN_LENGTH = 250
TOTAL_TRACK_LENGTH = 2 * (STRAIGHTAWAY_LENGTH + TURN_LENGTH)
CHARGING = 2
NORMAL = 1
RECOVERING = 0.75
SPEED_FACTOR = 1
ENDURANCE_FACTOR = 1
AGILITY_FACTOR = 1
END_MIN = 4
END_MAX = 7
VIG_MIN = 5
VIG_MAX = 8
ENERGY_MIN = 5
ENERGY_MAX = 10
ODDS_MIN = 1.1
ODDS_MAX = 3
SPEED_WEIGHT = 0.05
AGILITY_WEIGHT = 0.2
VIGOR_WEIGHT = 0.15
ENDURANCE_WEIGHT = 0.2
SPIRIT_WEIGHT = 0.2
ENERGY_WEIGHT = 0.2
WIN_MULT = 5
PLACE_MULT = 2
WEATHER_CONDITIONS = {
    "clear": 1.0,
    "foggy": 0.98,
    "rain": 0.96,
    "snow": 0.94,
    "thunderstorm": 0.92,
    "duststorm": 0.88,
    "deep freeze": 0.84,
    "hail": 0.80,
}
TRACK_CONDITIONS = {
    "clean": 1.0,
    "muddy": 0.90,
    "snow": 0.84,
    "deep mud": 0.82,
    "deep snow": 0.8,
    "frozen hard": 0.74,
}
PIG_NAMES = [
    "Hamlet",
    "Porkchop",
    "Baconator",
    "Snout Runner",
    "Truffle Shuffle",
    "BakingBits",
    "Superham",
    "Sir Oinksalot",
    "Wilbur Force",
    "Babe Ruth",
    "Pigasso",
    "Swinestein",
    "Hogwarts",
    "Piggy Smalls",
    "Notorious P.I.G.",
    "Hogzilla",
    "Snoop Hoggy Hog",
    "Porky Pint",
    "Chris P. Bacon",
    "Ham Solo",
    "Pigcasso",
    "Hog Hefner",
    "Frankenswine",
    "Curly Tail",
    "Pigtails",
    "Pigmalion",
    "Sausage Roller",
    "Hambone",
    "Miss Piggy Bank",
    "Pork Grind",
    "Pig Pen",
    "Rasher",
    "Swine Flew",
    "Swinona Ryder",
    "Chewbacon",
    "Hoggy Potter",
    "Scarlett O'Hambra",
    "Swinona Judd",
    "Jimmy Dean",
    "Pig Newton",
    "Boar-dom Buster",
    "Grunter Pan",
    "Hamwise Gamgee",
    "Porkahontas",
    "Chorizo Crusader",
    "Boar-becue",
    "Pigfoot",
    "Swine Gogh",
    "Mudonna",
    "Porkloin Piper",
    "Albert Einswine",
    "Hamibal Lecter",
    "Abra-ham Lincoln",
    "Bratwurst Bopper",
    "Hamela Anderson",
    "Harry Trotter",
    "Piggy Azalea",
    "Jon Ham",
    "Leonardo DiCapybara",
    "Marie Hamtoinette",
    "Pork Twain",
    "J.R.R. Tolkhogn",
    "Spamela Hamderson",
    "Hamlet's Ghost",
    "Napigleon Bonapork",
    "Trojan Horsetail",
    "Ribs Downey Jr.",
    "Amelia Swinehart",
    "Oinkstein",
    "Britney Spareribs",
    "Pignelope Cruz",
    "F. Scott Fitzboar",
    "Hammy Sosa",
    "Virginia Woof",
    "Swinburne",
    "Elvis Pigsley",
    "Hogney Dangerfield",
    "Porkahammas",
    "Hogarth Hughes",
    "Piggyback Rider",
    "Kevin Bacon",
    "Snortin' Norton",
    "Jennifer Lopigs",
    "Trotter White",
    "Winnie the Poohrk",
    "Jane Porker",
    "Snoutcast",
    "Hamela Hamford",
    "Sly Stallpork",
    "Porcasso",
    "Stephen Squealing",
    "Ruth Bacon Ginsboar",
    "Neil Porkstrong",
    "Oscar Mayer Wiener",
    "Anne of Green Gobbles",
    "Snouto Domoinko",
    "Swine Dion",
    "Porcules",
    "Quentin Tarantinoise",
    "Meryl Squeal",
    "Bacon Bitsy",
    "Swinestein",
    "Piggly Wiggly",
    "Oinkers Ahoy",
    "Snout Spout",
    "Hambone Flash",
    "Curly Tailor",
    "Trotter Trot",
    "Sir Oinksalot",
    "Hoggy Potter",
    "Mudpie Maverick",
    "Snortimus Prime",
    "Snortimus Maximus",
    "Sow Belly",
    "Pork Chopin",
    "Hogwarts Express",
    "Brisket Bouncer",
    "Chop Suey",
    "Sparerib Spike",
    "Snouter Space",
    "Pigasso",
    "Hammibal Lecter",
    "Porcinetor",
    "Boar Bunyan",
    "Sowpreme Court",
    "Riblet Racer",
    "Swine Song",
    "Pigtail Pilot",
    "Pigadilly Circus",
    "Chorizo Cruiser",
    "Porkchop Panache",
    "Hogwash",
    "Swine Diner",
    "Babe Ruth",
    "Porkerface",
    "Boar’d Game",
    "Pigathlon",
    "Sow-A-Long",
    "Baconeer",
    "Swiney Todd",
    "Porky Pygmalion",
    "Ham Solo",
    "Crackling Crusader",
    "Boaracle",
    "Porkadot",
    "Snoutcast",
    "Hamurai",
    "Pigwig",
    "Razorback Racer",
    "Piglet Poet",
    "SwineCraft",
    "PorknitePlayer",
    "BaconBitsBoss",
    "PigAxelFoley",
    "HamletHero",
    "SwineOfDuty",
    "PorcinePeaker",
    "SnoutSniper",
    "BoarBattler",
    "RindRacer",
    "HogOfWar",
    "SowSprinter",
    "TrotterTactician",
    "PigPenPwner",
    "StyStalker",
    "MudMaruder",
    "BoarBuster",
    "OinkerOperator",
    "SnoutScout",
    "RasherReaper",
    "GruntGamer",
    "BaconBrawler",
    "HamHockHacker",
    "SowSlayer",
    "RindRipper",
    "PigtailPwner",
    "SnortSniper",
    "BaconBandit",
    "SwineSoldier",
    "HambushHunter",
    "PorcinePirate",
    "BoarBehemoth",
    "SlopSergeant",
    "SwillSniper",
    "SquealSquad",
    "PorkPatroller",
    "HogHarrier",
    "BoarBlazer",
    "SwineStriker",
    "RasherRanger",
    "PignitionPilot",
    "HogHavoc",
    "PorcinePlatoon",
    "BoarBomber",
    "SnoutSaber",
    "RibletRogue",
    "SausageSpartan",
    "HogzillaHero",
    "Hamonizer",
    "TrotterTrooper",
    "PiggyPaddler",
    "CurlyTailCrusher",
    "Swinestein",
    "BaconBlast",
    "HogHearth",
    "RindRanger",
    "BoarBoss",
    "PiggyPwnage",
    "PorkerPlayer",
    "SnouterStriker",
    "BaconBro",
    "SowSaber",
    "PigskinPro",
    "RasherRider",
    "PorkChopChamp",
    "HogHurdler",
    "SwinerStalker",
    "HamHurdler",
    "SnoutSkirmisher",
    "SowSorcerer",
    "BoarBaron",
    "RindRebel",
    "PigletPugilist",
    "BaconBerserker",
    "SwineSorcerer",
    "HamHammer",
    "PorkyPaladin",
    "BoarBruiser",
    "SnoutSummoner",
    "RasherRogue",
    "TuskTactician",
    "PigstickPilot",
    "PorkyPirate",
    "HogHoncho",
    "BoarBuccaneer",
    "PigtailPlunderer",
    "SnortSnatcher",
    "BaconBuccaneer",
    "Swinosaur",
    "PorkPlatoon",
    "TrotterTracker",
    "RasherRaider",
    "BoarBandit",
    "SnoutStorm",
    "PigletParagon",
    "SowSpartan",
    "PorkyKnight",
    "RindRaider",
    "TuskTemplar",
    "BoarBattalion"
]
